name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: reality
    attributes:
      label: What happened?
      description: A brief descriprion of what happened?
      placeholder: Tell us what you see(Feel free to include screenshots)!
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        What was the expectation?.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages, exception stacktraces or memory dumps.
      placeholder: Actual behavior
    validations:
      required: true
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: |
        Did this work in a previous build or release of .NET Core, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
      placeholder: Regression?
    validations:
      required: false
  - type: textarea
    id: known-workarounds
    attributes:
      label: Known Workarounds
      description: |
        Please provide a description of any known workarounds.
      placeholder: Known Workarounds
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? Run `mgc --version` to see the version number.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What operating system are you experiencing the problem on?
      description: You can enter multiple operating systems using comma separated values.
      placeholder: Windows 10, Windows 11, MacOS Catalina, Ubuntu 22.04
  - type: dropdown
    id: arch
    attributes:
      label: What CPU architecture are you experiencing the problem on?
      multiple: true
      options:
        - x86
        - x64
        - arm
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Debug output
      description: Please copy and paste the output when using the `--debug`` flag. This will be automatically formatted into code, so no need for backticks.
      value: |
        <details><summary>Click to expand log</summary>
        ```
        Put your log output here
        ```
        </details>
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: |
        If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
      placeholder: Other information
    validations:
      required: false
